Cluster monitoring
redhat-developer/codeready-workspaces-chectl pull request #48
Opened 2020-11-05 17:01 UTC by flacatus

### What does this PR do?
This PR enables cluster monitoring description in Readme.md. Also change default olm suggested namespace name(`openshift-workspaces`).
Upstream related PR: https://github.com/che-incubator/chectl/pull/966

### What issues does this PR fix or reference?

2020-11-05 17:02 UTC, flacatus commented
cc @tolusha

2020-11-05 17:41 UTC, nickboldt commented on build/scripts/sync-chectl-to-crwctl.sh
> +      description: \`Enable cluster monitoring to scrape CodeReady Workspaces metrics in Prometheus.\n\
do we need to deviate from upstream here?

2020-11-05 17:49 UTC, nickboldt commented on build/scripts/sync-chectl-to-crwctl.sh
> +clusterMonitoringString="    'cluster-monitoring': boolean({\n\
for easier maintenance in future, this block could be read from upstream, then sed-replaced:

```
clusterMonitoringString="$(grep -A5 "'cluster-monitoring': boolean" src/commands/server/deploy.ts | sed -r -e "s/hidden: true/hidden: false/g")"; # echo -e "$clusterMonitoringString"
```

2020-11-05 17:50 UTC, nickboldt requested changes
see inline comments

2020-11-05 17:51 UTC, nickboldt commented on build/scripts/sync-chectl-to-crwctl.sh
> +		perl -0777 -p -i -e 's|(\ +'"'cluster-monitoring'"': boolean\({.*?}\),)| ${1} =~ /.+openshift.+/?"INSERT-CONTENT-HERE":${1}|gse' "${TARGETDIR}/${d}"
does this change depend on some uncommitted upstream change? I don't see cluster-monitoring in https://github.com/che-incubator/chectl/blob/master/src/commands/server/deploy.ts

2020-11-05 18:45 UTC, flacatus commented on build/scripts/sync-chectl-to-crwctl.sh
> +		perl -0777 -p -i -e 's|(\ +'"'cluster-monitoring'"': boolean\({.*?}\),)| ${1} =~ /.+openshift.+/?"INSERT-CONTENT-HERE":${1}|gse' "${TARGETDIR}/${d}"
It is not merged yet. 

che-incubator/chectl#966

2020-11-06 07:22 UTC, tolusha commented on build/scripts/sync-chectl-to-crwctl.sh
> +      description: \`Enable cluster monitoring to scrape CodeReady Workspaces metrics in Prometheus.\n\
Not in this case. We hide this option in chectl. That's why we have to readd in downstream.m

2020-11-06 13:49 UTC, nickboldt commented on build/scripts/sync-chectl-to-crwctl.sh
> +      description: \`Enable cluster monitoring to scrape CodeReady Workspaces metrics in Prometheus.\n\
so no need to inject "CodeReady Workspaces" into this line.

2020-11-06 15:37 UTC, nickboldt commented on build/scripts/sync-chectl-to-crwctl.sh
> +		perl -0777 -p -i -e 's|(\ +'"'cluster-monitoring'"': boolean\({.*?}\),)| ${1} =~ /.+openshift.+/?"INSERT-CONTENT-HERE":${1}|gse' "${TARGETDIR}/${d}"
Narrator: it was merged.

2020-11-10 13:58 UTC, flacatus commented on build/scripts/sync-chectl-to-crwctl.sh
> +clusterMonitoringString="    'cluster-monitoring': boolean({\n\
@nickboldt How we spoke recently if I'll do in this way I'll have some problems by applying changes with sed but I have a lot of problems with sed.
I've tried for example 
perl -0777 -p -i -e 's|(\ +'"'cluster-monitoring'"': boolean\({.*?}\),)| ${1} =~ /.+openshift.+/?"INSERT-CONTENT-HERE":${1}|gse' "${TARGETDIR}/${d}"
```sed -r -e "s|INSERT-CONTENT-HERE|"\\\\ \\${clusterMonitoringString}$"|g" -i "${TARGETDIR}/${d}"```
Can you help me please to find the right sed command?

2020-11-11 14:19 UTC, nickboldt approved these changes

2020-11-11 14:19 UTC, merged